### ISSUE TITLE
[Feature Request] Provide implementation for LRU cache

### ISSUE THREAD

**Issue by Ernyoke** [esimov/gogu#5]
[Least recently used (LRU) cache](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)) is a data structure which provides O(1) time access for any stored value based on a key, while having the ability to provide an O(1) access to the last used value as well. The size of the cache is limited, when this limit is reached, the oldest values will be evicted. 

A possible implementation for this data structure can be found in this PR: https://github.com/esimov/gogu/pull/4

Depending on your choice, it could be merged, or you could discard it and use it as a basis of a possible future implementation.

**Comment by esimov** [comment]
Thanks a lot for your contribution. I don't have access to the code right now, but I will check it as soon as I can.

**Comment by esimov** [comment]
@Ernyoke good work, your PR has been merged back to the master branch. Thank you very much for the contribution.
